//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.05.24 at 01:58:11 PM CDT
//


package sx.cfdi.ine;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Entidad" maxOccurs="64" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Contabilidad" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="IdContabilidad" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                 &lt;totalDigits value="6"/>
 *                                 &lt;fractionDigits value="0"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ClaveEntidad" use="required" type="{http://www.sat.gob.mx/ine}t_ClaveEntidad" />
 *                 &lt;attribute name="Ambito">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.sat.gob.mx/ine}t_Ambito">
 *                       &lt;whiteSpace value="collapse"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Version" use="required" fixed="1.0">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;whiteSpace value="collapse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="TipoProceso" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.sat.gob.mx/ine}t_TipoProc">
 *             &lt;whiteSpace value="collapse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="TipoComite">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.sat.gob.mx/ine}t_TipoComite">
 *             &lt;whiteSpace value="collapse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="IdContabilidad">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;totalDigits value="6"/>
 *             &lt;fractionDigits value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entidad"
})
@XmlRootElement(name = "INE")
public class INE {

    @XmlElement(name = "Entidad")
    protected List<INE.Entidad> entidad;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "TipoProceso", required = true)
    protected TTipoProc tipoProceso;
    @XmlAttribute(name = "TipoComite")
    protected TTipoComite tipoComite;
    @XmlAttribute(name = "IdContabilidad")
    protected Integer idContabilidad;

    /**
     * Gets the value of the entidad property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entidad property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntidad().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link INE.Entidad }
     *
     *
     */
    public List<INE.Entidad> getEntidad() {
        if (entidad == null) {
            entidad = new ArrayList<INE.Entidad>();
        }
        return this.entidad;
    }

    /**
     * Gets the value of the version property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the tipoProceso property.
     *
     * @return
     *     possible object is
     *     {@link TTipoProc }
     *
     */
    public TTipoProc getTipoProceso() {
        return tipoProceso;
    }

    /**
     * Sets the value of the tipoProceso property.
     *
     * @param value
     *     allowed object is
     *     {@link TTipoProc }
     *
     */
    public void setTipoProceso(TTipoProc value) {
        this.tipoProceso = value;
    }

    /**
     * Gets the value of the tipoComite property.
     *
     * @return
     *     possible object is
     *     {@link TTipoComite }
     *
     */
    public TTipoComite getTipoComite() {
        return tipoComite;
    }

    /**
     * Sets the value of the tipoComite property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTipoComite }
     *     
     */
    public void setTipoComite(TTipoComite value) {
        this.tipoComite = value;
    }

    /**
     * Gets the value of the idContabilidad property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdContabilidad() {
        return idContabilidad;
    }

    /**
     * Sets the value of the idContabilidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdContabilidad(Integer value) {
        this.idContabilidad = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Contabilidad" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="IdContabilidad" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                       &lt;totalDigits value="6"/>
     *                       &lt;fractionDigits value="0"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="ClaveEntidad" use="required" type="{http://www.sat.gob.mx/ine}t_ClaveEntidad" />
     *       &lt;attribute name="Ambito">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.sat.gob.mx/ine}t_Ambito">
     *             &lt;whiteSpace value="collapse"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contabilidad"
    })
    public static class Entidad {

        @XmlElement(name = "Contabilidad")
        protected List<INE.Entidad.Contabilidad> contabilidad;
        @XmlAttribute(name = "ClaveEntidad", required = true)
        protected TClaveEntidad claveEntidad;
        @XmlAttribute(name = "Ambito")
        protected TAmbito ambito;

        /**
         * Gets the value of the contabilidad property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contabilidad property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContabilidad().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link INE.Entidad.Contabilidad }
         * 
         * 
         */
        public List<INE.Entidad.Contabilidad> getContabilidad() {
            if (contabilidad == null) {
                contabilidad = new ArrayList<INE.Entidad.Contabilidad>();
            }
            return this.contabilidad;
        }

        /**
         * Gets the value of the claveEntidad property.
         * 
         * @return
         *     possible object is
         *     {@link TClaveEntidad }
         *     
         */
        public TClaveEntidad getClaveEntidad() {
            return claveEntidad;
        }

        /**
         * Sets the value of the claveEntidad property.
         * 
         * @param value
         *     allowed object is
         *     {@link TClaveEntidad }
         *     
         */
        public void setClaveEntidad(TClaveEntidad value) {
            this.claveEntidad = value;
        }

        /**
         * Gets the value of the ambito property.
         * 
         * @return
         *     possible object is
         *     {@link TAmbito }
         *     
         */
        public TAmbito getAmbito() {
            return ambito;
        }

        /**
         * Sets the value of the ambito property.
         * 
         * @param value
         *     allowed object is
         *     {@link TAmbito }
         *     
         */
        public void setAmbito(TAmbito value) {
            this.ambito = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="IdContabilidad" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *             &lt;totalDigits value="6"/>
         *             &lt;fractionDigits value="0"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Contabilidad {

            @XmlAttribute(name = "IdContabilidad", required = true)
            protected int idContabilidad;

            /**
             * Gets the value of the idContabilidad property.
             * 
             */
            public int getIdContabilidad() {
                return idContabilidad;
            }

            /**
             * Sets the value of the idContabilidad property.
             * 
             */
            public void setIdContabilidad(int value) {
                this.idContabilidad = value;
            }

        }

    }

}
