//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.24 at 01:58:11 PM CDT 
//


package sx.cfdi.ine;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_ClaveEntidad.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="t_ClaveEntidad">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AGU"/>
 *     &lt;enumeration value="BCN"/>
 *     &lt;enumeration value="BCS"/>
 *     &lt;enumeration value="CAM"/>
 *     &lt;enumeration value="CHP"/>
 *     &lt;enumeration value="CHH"/>
 *     &lt;enumeration value="COA"/>
 *     &lt;enumeration value="COL"/>
 *     &lt;enumeration value="DIF"/>
 *     &lt;enumeration value="DUR"/>
 *     &lt;enumeration value="GUA"/>
 *     &lt;enumeration value="GRO"/>
 *     &lt;enumeration value="HID"/>
 *     &lt;enumeration value="JAL"/>
 *     &lt;enumeration value="MEX"/>
 *     &lt;enumeration value="MIC"/>
 *     &lt;enumeration value="MOR"/>
 *     &lt;enumeration value="NAY"/>
 *     &lt;enumeration value="NLE"/>
 *     &lt;enumeration value="OAX"/>
 *     &lt;enumeration value="PUE"/>
 *     &lt;enumeration value="QTO"/>
 *     &lt;enumeration value="ROO"/>
 *     &lt;enumeration value="SLP"/>
 *     &lt;enumeration value="SIN"/>
 *     &lt;enumeration value="SON"/>
 *     &lt;enumeration value="TAB"/>
 *     &lt;enumeration value="TAM"/>
 *     &lt;enumeration value="TLA"/>
 *     &lt;enumeration value="VER"/>
 *     &lt;enumeration value="YUC"/>
 *     &lt;enumeration value="ZAC"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "t_ClaveEntidad")
@XmlEnum
public enum TClaveEntidad {

    AGU,
    BCN,
    BCS,
    CAM,
    CHP,
    CHH,
    COA,
    COL,
    DIF,
    DUR,
    GUA,
    GRO,
    HID,
    JAL,
    MEX,
    MIC,
    MOR,
    NAY,
    NLE,
    OAX,
    PUE,
    QTO,
    ROO,
    SLP,
    SIN,
    SON,
    TAB,
    TAM,
    TLA,
    VER,
    YUC,
    ZAC;

    public String value() {
        return name();
    }

    public static TClaveEntidad fromValue(String v) {
        return valueOf(v);
    }

}
