//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.24 at 01:58:11 PM CDT 
//


package sx.cfdi.ine;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_TipoComite.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="t_TipoComite">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Ejecutivo Nacional"/>
 *     &lt;enumeration value="Ejecutivo Estatal"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "t_TipoComite")
@XmlEnum
public enum TTipoComite {

    @XmlEnumValue("Ejecutivo Nacional")
    EJECUTIVO_NACIONAL("Ejecutivo Nacional"),
    @XmlEnumValue("Ejecutivo Estatal")
    EJECUTIVO_ESTATAL("Ejecutivo Estatal");
    private final String value;

    TTipoComite(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTipoComite fromValue(String v) {
        for (TTipoComite c: TTipoComite.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
